
apiVersion: batch/v1
kind: Job
metadata:
  name: foojob
  namespace: default
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: endlesssidecar
        image: fedora:32
        command: ["/bin/bash"]
        args: ["-c", "sleep infinity"]
      - name: foojob
        image: fedora:32
        command: ["/bin/bash"]
        args: ["/scripts-dir/run.sh"]
        volumeMounts:
        - name: scripts-vol
          mountPath: /scripts-dir
      volumes:
      - name: scripts-vol
        configMap:
          name: scripts-configmap
